/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class katarina_petrovic_memorygame_JNIexample */

#ifndef _Included_katarina_petrovic_memorygame_JNIexample
#define _Included_katarina_petrovic_memorygame_JNIexample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     katarina_petrovic_memorygame_JNIexample
 * Method:    racunajProcenat
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_katarina_petrovic_memorygame_JNIexample_racunajProcenat
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
